### ISSUE TITLE
build_db fails - missing CREATE_TABLE

### ISSUE THREAD

**Issue by hassanshamim** [hackoregon/urbandev-etl#37]
[here](https://github.com/hackoregon/urbandev-etl/blob/master/postgresql/scripts/bin/build_db#L116)  errors as:
`/urbandev-etl/postgresql/scripts/bin/../sql/CREATE-TABLE-crime.sql: No such file or directory`

**Comment by meyersj** [comment]
`CREATE-TABLE-crime.sql` is too big for github (110MB). You can download from https://files.slack.com/files-pri/T0LK1LTK3-F1C61CU04/download/create-table-crime.sql and placed in `postgresql/scripts/data-loaders/data`.

Will look into github large file storage (https://git-lfs.github.com/?utm_source=github_site&utm_medium=blog&utm_campaign=gitlfs).

For the time being maybe a conditional should check if that file exists and output a nice message that it should be downloaded from slack.
